<?php
/**
 * Autoloader for the bundled php-vips library.
 *
 * This file is generated by tools/php-vips/installer.sh.
 * Do not edit directly.
 *
 * Vendored from https://github.com/libvips/php-vips.git at v2.6.1 (6dbba1bb3a4ba1e39edb71016a2aa6da5bff32ee).
 *
 * @package WordPress
 * @subpackage Image_Editor
 * @since 7.2.0
 */

spl_autoload_register(
	static function ( $class_name ) {
		// Namespace prefix for php-vips.
		$vips_prefix     = 'Jcupitt\\Vips\\';
		$vips_prefix_len = 13; // strlen( 'Jcupitt\\Vips\\' )

		// Namespace prefix for scoped dependencies (Psr\Log\*).
		$scoped_prefix     = 'WordPress\\VipsDependencies\\';
		$scoped_prefix_len = 27; // strlen( 'WordPress\\VipsDependencies\\' )

		$base_dir = __DIR__;

		// 1. Jcupitt\Vips\* → src/
		if ( 0 === strncmp( $class_name, $vips_prefix, $vips_prefix_len ) ) {
			$relative_class = substr( $class_name, $vips_prefix_len );
			$file           = $base_dir . '/src/' . str_replace( '\\', '/', $relative_class ) . '.php';
			if ( file_exists( $file ) ) {
				require $file;
			}
			return;
		}

		// 2. WordPress\VipsDependencies\* → third-party/ (strip prefix).
		if ( 0 === strncmp( $class_name, $scoped_prefix, $scoped_prefix_len ) ) {
			$relative_class = substr( $class_name, $scoped_prefix_len );
			$file           = $base_dir . '/third-party/' . str_replace( '\\', '/', $relative_class ) . '.php';
			if ( file_exists( $file ) ) {
				require $file;
			}
			return;
		}
	}
);
