<?php

/**
 * @group ms-required
 * @group multisite
 *
 * @covers ::wpmu_activate_signup
 */
class Tests_Multisite_wpmuActivateSignup extends WP_UnitTestCase {

	/**
	 * Signs up a user and captures the URL payload from the after_signup_user action.
	 *
	 * @param string $login
	 * @param string $email
	 * @return array{ key: string }
	 */
	private function signup_user( $login, $email ) {
		$data     = array( 'key' => null );
		$listener = static function ( $u, $e, $payload ) use ( &$data ) {
			$data['key'] = $payload;
		};
		add_filter( 'wpmu_signup_user_notification', '__return_false' );
		add_action( 'after_signup_user', $listener, 10, 3 );
		wpmu_signup_user( $login, $email );
		remove_action( 'after_signup_user', $listener, 10 );
		remove_filter( 'wpmu_signup_user_notification', '__return_false' );
		return $data;
	}

	/**
	 * @ticket 38474
	 */
	public function test_signup_user_stores_hmac_hash() {
		global $wpdb;

		$this->signup_user( 'tuser38474a', 'tuser38474a@example.com' );

		$stored = $wpdb->get_var( "SELECT activation_key FROM $wpdb->signups WHERE user_login = 'tuser38474a'" );

		$this->assertMatchesRegularExpression( '/^[A-Za-z0-9+\/]{43}=$/', $stored, 'Stored activation key must be a 44-char base64-encoded SHA-256 HMAC.' );
	}

	/**
	 * @ticket 38474
	 */
	public function test_activate_signup_succeeds_with_valid_payload() {
		add_filter( 'wpmu_welcome_user_notification', '__return_false' );

		$data   = $this->signup_user( 'tuser38474b', 'tuser38474b@example.com' );
		$result = wpmu_activate_signup( $data['key'] );

		remove_filter( 'wpmu_welcome_user_notification', '__return_false' );

		$this->assertIsArray( $result );
		$this->assertArrayHasKey( 'user_id', $result );
	}

	/**
	 * @ticket 38474
	 */
	public function test_activate_signup_fails_with_wrong_key() {
		$this->signup_user( 'tuser38474c', 'tuser38474c@example.com' );
		$result = wpmu_activate_signup( 'thisisnottherightkey' );

		$this->assertWPError( $result );
		$this->assertSame( 'invalid_key', $result->get_error_code() );
	}

	/**
	 * Legacy plain-text keys (stored before the hashing upgrade) must still activate
	 * successfully so that users with pending activation emails are not broken by the upgrade.
	 *
	 * @ticket 38474
	 */
	public function test_activate_signup_allows_legacy_plain_text_key() {
		global $wpdb;

		add_filter( 'wpmu_welcome_user_notification', '__return_false' );

		// Legacy keys are exactly 16 lowercase hex characters (generated by substr(md5(...), 0, 16)).
		$plain_key = 'abc1234567890def';
		$wpdb->insert(
			$wpdb->signups,
			array(
				'domain'         => '',
				'path'           => '',
				'title'          => '',
				'user_login'     => 'legacyuser38474',
				'user_email'     => 'legacy38474@example.com',
				'registered'     => current_time( 'mysql', true ),
				'activation_key' => $plain_key,
				'meta'           => serialize( array() ),
			)
		);

		$result = wpmu_activate_signup( $plain_key );

		remove_filter( 'wpmu_welcome_user_notification', '__return_false' );

		$this->assertIsArray( $result, 'Legacy plain-text activation keys must still work after upgrade.' );
		$this->assertArrayHasKey( 'user_id', $result );
	}

	/**
	 * A wrong key against a legacy plain-text row must still be rejected.
	 *
	 * @ticket 38474
	 */
	public function test_activate_signup_rejects_wrong_key_against_legacy_row() {
		global $wpdb;

		$plain_key = 'abc1234567890abc';
		$wpdb->insert(
			$wpdb->signups,
			array(
				'domain'         => '',
				'path'           => '',
				'title'          => '',
				'user_login'     => 'legacyuser38474b',
				'user_email'     => 'legacy38474b@example.com',
				'registered'     => current_time( 'mysql', true ),
				'activation_key' => $plain_key,
				'meta'           => serialize( array() ),
			)
		);

		// A key that looks like a legacy key but doesn't match the stored value.
		$result = wpmu_activate_signup( '0000000000000000' );

		$this->assertWPError( $result );
		$this->assertSame( 'invalid_key', $result->get_error_code() );
	}

	/**
	 * @ticket 38474
	 */
	public function test_activate_signup_rejects_expired_key() {
		$data = $this->signup_user( 'tuser38474e', 'tuser38474e@example.com' );

		add_filter(
			'activate_signup_expiration',
			static function () {
				return -1;
			}
		);
		$result = wpmu_activate_signup( $data['key'] );
		remove_all_filters( 'activate_signup_expiration' );

		$this->assertWPError( $result );
		$this->assertSame( 'expired_key', $result->get_error_code() );
	}

	/**
	 * @ticket 38474
	 */
	public function test_activate_signup_expiration_filter_is_applied() {
		$data          = $this->signup_user( 'tuser38474f', 'tuser38474f@example.com' );
		$filter_called = false;
		$filter        = static function ( $duration ) use ( &$filter_called ) {
			$filter_called = true;
			return $duration;
		};

		add_filter( 'activate_signup_expiration', $filter );
		wpmu_activate_signup( $data['key'] );
		remove_filter( 'activate_signup_expiration', $filter );

		$this->assertTrue( $filter_called );
	}

	/**
	 * @ticket 38474
	 *
	 * @covers ::wpmu_signup_user_notification
	 */
	public function test_signup_user_notification_url_contains_key_payload() {
		$data = $this->signup_user( 'tuser38474g', 'tuser38474g@example.com' );

		$captured = '';
		$capture  = static function ( $args ) use ( &$captured ) {
			$captured = $args['message'];
			return $args;
		};

		add_filter( 'wp_mail', $capture );
		wpmu_signup_user_notification( 'tuser38474g', 'tuser38474g@example.com', $data['key'], array() );
		remove_filter( 'wp_mail', $capture );

		$this->assertStringContainsString( 'wp-activate.php?key=', $captured );
	}

	/**
	 * A legacy plain-text key registered before the expiration window must be rejected.
	 *
	 * @ticket 38474
	 */
	public function test_activate_signup_rejects_expired_legacy_key() {
		global $wpdb;

		$plain_key = 'aaaabbbbccccdddd';
		$wpdb->insert(
			$wpdb->signups,
			array(
				'domain'         => '',
				'path'           => '',
				'title'          => '',
				'user_login'     => 'legacyuser38474c',
				'user_email'     => 'legacy38474c@example.com',
				'registered'     => gmdate( 'Y-m-d H:i:s', time() - DAY_IN_SECONDS - 1 ),
				'activation_key' => $plain_key,
				'meta'           => serialize( array() ),
			)
		);

		$result = wpmu_activate_signup( $plain_key );

		$this->assertWPError( $result );
		$this->assertSame( 'expired_key', $result->get_error_code() );
	}

	/**
	 * Ensure the stored activation key fits within 60 characters to account for sites
	 * that have not updated their table schema (e.g. those using DO_NOT_UPGRADE_GLOBAL_TABLES).
	 *
	 * @ticket 38474
	 */
	public function test_activation_key_fits_legacy_column_length() {
		global $wpdb;

		$this->signup_user( 'tuser38474h', 'tuser38474h@example.com' );

		$stored = $wpdb->get_var( "SELECT activation_key FROM $wpdb->signups WHERE user_login = 'tuser38474h'" );

		$this->assertNotNull( $stored );
		$this->assertLessThanOrEqual( 60, strlen( $stored ), 'Stored activation key must be no longer than 60 characters for legacy schema compatibility.' );
	}
}
