<?php

/**
 * Tests for the Site Health debug information.
 *
 * @group admin
 * @group site-health
 * @coversDefaultClass WP_Debug_Data
 */
class Tests_Admin_wpDebugData extends WP_UnitTestCase {
	/**
	 * Temporary document root.
	 *
	 * @var string
	 */
	private $document_root;

	/**
	 * Original server variables.
	 *
	 * @var array
	 */
	private $server;

	/**
	 * Original rewrite component.
	 *
	 * @var WP_Rewrite
	 */
	private $rewrite;

	public function set_up() {
		parent::set_up();

		require_once ABSPATH . 'wp-admin/includes/class-wp-debug-data.php';

		$this->server        = $_SERVER;
		$this->rewrite       = clone $GLOBALS['wp_rewrite'];
		$this->document_root = get_temp_dir() . uniqid( 'robots-debug-', true );
		mkdir( $this->document_root );
		mkdir( $this->document_root . '/blog' );
	}

	public function tear_down() {
		foreach ( array( '/robots.txt', '/blog/robots.txt' ) as $path ) {
			$path = $this->document_root . $path;
			if ( is_file( $path ) ) {
				unlink( $path );
			} elseif ( is_dir( $path ) ) {
				rmdir( $path );
			}
		}
		rmdir( $this->document_root . '/blog' );
		rmdir( $this->document_root );

		$_SERVER               = $this->server;
		$GLOBALS['wp_rewrite'] = $this->rewrite;

		parent::tear_down();
	}

	/**
	 * @ticket 66060
	 * @dataProvider data_robots_txt
	 * @covers ::get_robots_txt
	 *
	 * @param array       $args     Server and site configuration.
	 * @param bool|string $expected Expected static file debug value.
	 */
	public function test_robots_txt( $args, $expected ) {
		global $wp_rewrite;

		$args = array_merge(
			array(
				'home'           => 'http://example.org',
				'home_directory' => null,
				'document_root'  => 'valid',
				'file'           => 'none',
				'permalinks'     => '/%postname%/',
				'rewrite'        => true,
			),
			$args
		);

		$home_path = (string) wp_parse_url( $args['home'], PHP_URL_PATH );
		update_option( 'home', $args['home'] );
		update_option( 'siteurl', untrailingslashit( $args['home'] ) . '/wp' );
		$home_directory             = null === $args['home_directory'] ? untrailingslashit( $home_path ) : $args['home_directory'];
		$_SERVER['SCRIPT_FILENAME'] = $this->document_root . $home_directory . '/wp/wp-admin/site-health.php';
		$_SERVER['DOCUMENT_ROOT']   = $this->document_root;

		switch ( $args['document_root'] ) {
			case 'missing':
				unset( $_SERVER['DOCUMENT_ROOT'] );
				break;
			case 'empty':
				$_SERVER['DOCUMENT_ROOT'] = '';
				break;
			case 'invalid':
				$_SERVER['DOCUMENT_ROOT'] .= '/missing';
				break;
			case 'trailing_slash':
				$_SERVER['DOCUMENT_ROOT'] .= '/';
				break;
		}

		$this->assertSame( $this->document_root . $home_directory . '/', get_home_path(), 'The fixture must resolve to the intended home directory.' );

		if ( in_array( $args['file'], array( 'root', 'both' ), true ) ) {
			file_put_contents( $this->document_root . '/robots.txt', "User-agent: *\n" );
		}
		if ( in_array( $args['file'], array( 'subdirectory', 'both' ), true ) ) {
			file_put_contents( $this->document_root . '/blog/robots.txt', "User-agent: *\n" );
		}
		if ( 'directory' === $args['file'] ) {
			mkdir( $this->document_root . '/robots.txt' );
		}

		add_filter( 'got_url_rewrite', $args['rewrite'] ? '__return_true' : '__return_false' );
		update_option( 'permalink_structure', $args['permalinks'] );
		$wp_rewrite->init();
		$method = new ReflectionMethod( 'WP_Debug_Data', 'get_robots_txt' );
		if ( PHP_VERSION_ID < 80100 ) {
			$method->setAccessible( true );
		}
		$field = $method->invoke( null );

		$this->assertSame( 'unsupported' === $expected ? true : $expected, $field['debug'] );
		$this->assertSame( 'robots.txt', $field['label'] );
		if ( true === $expected ) {
			$this->assertSame( 'Your site is using a static robots.txt file. WordPress cannot dynamically serve one.', $field['value'] );
		} elseif ( false === $expected ) {
			$this->assertSame( 'Your site is using the dynamic robots.txt file which is generated by WordPress.', $field['value'] );
		} elseif ( 'unsupported' === $expected ) {
			$this->assertSame( 'WordPress cannot dynamically serve a robots.txt file due to a lack of rewrite rule support.', $field['value'] );
		} else {
			$this->assertStringContainsString( 'Unable to determine', $field['value'] );
		}
	}

	/**
	 * Subdirectory network sites share the host's root robots.txt file.
	 *
	 * @ticket 66060
	 * @group ms-required
	 * @covers ::get_robots_txt
	 */
	public function test_multisite_subdirectory_uses_shared_root_file() {
		$site_id = self::factory()->blog->create( array( 'path' => '/child/' ) );
		file_put_contents( $this->document_root . '/robots.txt', "User-agent: *\n" );
		$_SERVER['DOCUMENT_ROOT'] = $this->document_root;

		$method = new ReflectionMethod( 'WP_Debug_Data', 'get_robots_txt' );
		if ( PHP_VERSION_ID < 80100 ) {
			$method->setAccessible( true );
		}

		$main_site_field = $method->invoke( null );
		switch_to_blog( $site_id );
		try {
			$child_site_field = $method->invoke( null );
			$this->assertTrue( $child_site_field['debug'] );
			$this->assertSame( $main_site_field, $child_site_field );
		} finally {
			restore_current_blog();
		}
	}

	/**
	 * Configurations for robots.txt reporting, also run by the multisite suite.
	 *
	 * @return array
	 */
	public function data_robots_txt() {
		$cases = array(
			'root static file'                    => array( array( 'file' => 'root' ), true ),
			'root dynamic with core in subdir'    => array( array(), false ),
			'root home with trailing slash'       => array( array( 'home' => 'http://example.org/' ), false ),
			'subdirectory site with root file'    => array(
				array(
					'home' => 'http://example.org/blog',
					'file' => 'root',
				),
				true,
			),
			'root file takes precedence'          => array(
				array(
					'home' => 'http://example.org/blog',
					'file' => 'both',
				),
				true,
			),
			'subdirectory file is ignored'        => array(
				array(
					'home' => 'http://example.org/blog',
					'file' => 'subdirectory',
				),
				'unknown',
			),
			'subdirectory without files'          => array( array( 'home' => 'http://example.org/blog' ), 'unknown' ),
			'subdomain dynamic'                   => array( array( 'home' => 'http://sub.example.org' ), false ),
			'mapped domain static'                => array(
				array(
					'home' => 'https://mapped.example.net',
					'file' => 'root',
				),
				true,
			),
			'mapped domain dynamic'               => array( array( 'home' => 'https://mapped.example.net' ), false ),
			'missing document root fallback'      => array(
				array(
					'document_root' => 'missing',
					'file'          => 'root',
				),
				true,
			),
			'empty document root fallback'        => array(
				array(
					'document_root' => 'empty',
					'file'          => 'root',
				),
				true,
			),
			'invalid document root fallback'      => array(
				array(
					'document_root' => 'invalid',
					'file'          => 'root',
				),
				true,
			),
			'document root with trailing slash'   => array(
				array(
					'document_root' => 'trailing_slash',
					'file'          => 'root',
				),
				true,
			),
			'no fallback to subdirectory file'    => array(
				array(
					'home'          => 'http://example.org/blog',
					'document_root' => 'missing',
					'file'          => 'subdirectory',
				),
				'unknown',
			),
			'plain permalinks'                    => array( array( 'permalinks' => '' ), 'unknown' ),
			'index permalinks'                    => array( array( 'permalinks' => '/index.php/%postname%/' ), 'unknown' ),
			'no rewrite support'                  => array( array( 'rewrite' => false ), 'unsupported' ),
			'static file without rewrite support' => array(
				array(
					'file'    => 'root',
					'rewrite' => false,
				),
				true,
			),
			'directory is not a static file'      => array( array( 'file' => 'directory' ), 'unknown' ),
		);

		// Root URL served from a different filesystem directory, such as an alias.
		foreach ( array(
			'root'         => true,
			'subdirectory' => 'unknown',
			'both'         => true,
			'none'         => false,
		) as $file => $expected ) {
			$cases[ 'different document and home roots: ' . $file ] = array(
				array(
					'home_directory' => '/blog',
					'file'           => $file,
				),
				$expected,
			);
		}

		/*
		 * For each location, expectations are ordered as:
		 * file + pretty, file + plain, no file + pretty, no file + plain.
		 * An undiscoverable host-root file must not be inferred from a child site.
		 */
		$locations = array(
			'root, known document root'     => array( '', 'valid', array( true, true, false, 'unknown' ) ),
			'root, missing document root'   => array( '', 'missing', array( true, true, false, 'unknown' ) ),
			'subdir, known document root'   => array( '/blog', 'valid', array( true, true, 'unknown', 'unknown' ) ),
			'subdir, missing document root' => array( '/blog', 'missing', array( 'unknown', 'unknown', 'unknown', 'unknown' ) ),
		);
		foreach ( $locations as $label => $location ) {
			$index = 0;
			foreach ( array( 'root', 'none' ) as $file ) {
				foreach ( array( '/%postname%/', '' ) as $permalinks ) {
					$cases[ 'matrix: ' . $label . ', file=' . $file . ', permalinks=' . $permalinks ] = array(
						array(
							'home'          => 'http://example.org' . $location[0],
							'document_root' => $location[1],
							'file'          => $file,
							'permalinks'    => $permalinks,
						),
						$location[2][ $index++ ],
					);
				}
			}
		}

		return $cases;
	}
}
