<?php

/**
 * Tests for the get_calendar() function.
 *
 * @group general-template
 *
 * @covers ::get_calendar
 */

class GetCalendarTest extends WP_UnitTestCase {
	protected $post_id;

	public function set_up() {
		parent::set_up();
		$this->post_id = self::factory()->post->create();
	}

	/**
	 * Tests that the get_calendar function returns HTML for the calendar of the current month.
	 *
	 * @ticket 61732
	 */
	public function testGet_calendar_returns_calendar_html_for_current_month() {
		$current_month_calendar_html = '<caption>' . gmdate( 'F Y' ) . '</caption>';

		$output = get_calendar( true, false );

		$this->assertStringContainsString( $current_month_calendar_html, $output );
	}

	/**
	 * Tests that the get_calendar function returns the calendar HTML correctly when the month value exceeds 12.
	 *
	 * @ticket 61732
	 */
	public function testGet_calendar_returns_jan_m_is_more_than_12() {
		global $m;
		$m = 123456;

		$calendar_html = get_calendar( true, false );

		$this->assertStringContainsString( '<caption>January 1234</caption>', $calendar_html );
	}

	/**
	 * Tests that the calendar generated by get_calendar() correctly interprets
	 * the global variable $m as 123409 and ensures September is displayed properly
	 * in the caption as "September 1234".
	 *
	 * @ticket 61732
	 */
	public function testGet_calendar_returns_sept_m_is_09() {
		global $m;
		$m = 123409;

		$calendar_html = get_calendar( true, false );

		$this->assertStringContainsString( '<caption>September 1234</caption>', $calendar_html );
	}

	/**
	 * Tests that the calendar generated by get_calendar() starts with Monday
	 * and ends with Sunday when the week starts on Monday.
	 *
	 * @ticket 61732
	 */
	public function testGet_calendar_day_of_week_starts_monday() {
		$calendar_html = get_calendar( true, false );

		$this->assertMatchesRegularExpression( '#aria-label="Monday">M.*aria-label="Sunday">S#s', $calendar_html );
	}

	/**
	 * Tests that the calendar generated by get_calendar() function starts the week on Sunday.
	 *
	 * It adds a filter to override the 'start_of_week' option to Sunday (represented by 0),
	 * then asserts that the produced HTML contains the days in the correct order
	 * starting with Sunday.
	 *
	 * @ticket 61732
	 *
	 */
	public function testGet_calendar_day_of_week_starts_sunday() {

		add_filter(
			'pre_option_start_of_week',
			function () {
				return 0;
			}
		);

		$calendar_html = get_calendar( true, false );

		$this->assertMatchesRegularExpression( '#aria-label="Sunday">S.*aria-label="Monday">M#s', $calendar_html );
	}

	/*
	 * Test that the get_calendar function return HTML that represents the last day of October, day 31
	 * in positive non UTC timezone (i.e: UTC+1)
	 *
	 * @ticket 61732
	 */
	public function test_Get_calendar_returns_post_day_31_in_october_in_non_UTC_timezone() {

		// date_default_timezone_set( 'Europe/Paris' );
		$day_31_in_calendar_html = '<td><a href="http://example.org/?m=20241031" aria-label="Posts published on October 31, 2024">31</a>';
		$post_id                 = self::factory()->post->create( array( 'post_date' => '2024-10-31 10:00:00' ) );
		self::factory()->post->create( array( 'post_date' => '2024-10-30 10:00:00' ) );
		global $year, $monthnum, $wpdb;
		$year     = 2024;
		$monthnum = 10;

		$output = get_calendar( true, false );

		$this->assertStringContainsString( $day_31_in_calendar_html, $output );
	}


	/**
	 * Tests that get_calendar handles month boundaries correctly.
	 *
	 * This test verifies that get_calendar properly handles the transition
	 * between months with different numbers of days, particularly when
	 * the current month has fewer than 31 days.
	 *
	 * @ticket 61732
	 */
	public function test_get_calendar_handles_month_boundaries_correctly() {
		// Create a post in November (which has 30 days)
		self::factory()->post->create( array( 'post_date' => '2024-11-15 10:00:00' ) );

		// Set the current view to November 2024
		global $year, $monthnum, $wpdb;
		$year     = 2024;
		$monthnum = 11;

		// Clear any previous errors
		$wpdb->last_error = '';

		// Get the calendar for November (which should try to find posts in December)
		$output = get_calendar( true, false );

		// Verify no SQL errors occurred
		$this->assertSame( '', $wpdb->last_error, 'SQL error occurred when handling month boundary' );

		// Verify the calendar contains November
		$this->assertStringContainsString( '<caption>November 2024</caption>', $output );
	}

	/*
	 * Test that get_calendar function doesn't trigger wpdb errors in positive non UTC timezone (i.e: UTC+1)
	 *
	 * @ticket 61732
	 */
	public function test_Get_calendar_no_database_errors_in_non_UTC_timezone() {
		self::factory()->post->create( array( 'post_date' => '2024-11-15 10:00:00' ) );
		global $year, $monthnum, $wpdb;
		$year     = 2024;
		$monthnum = 11;

		date_default_timezone_set( 'Europe/Paris' );

		// Clear any previous errors
		$wpdb->last_error = '';

		$output = get_calendar( true, false );

		// Verify no SQL errors occurred
		$this->assertSame( '', $wpdb->last_error, 'SQL error occurred when handling month boundary' );

		// Verify the calendar contains November
		$this->assertStringContainsString( '<caption>November 2024</caption>', $output );
		date_default_timezone_set( 'UTC' );
	}
}
