<?php

require_once ABSPATH . WPINC . '/class-wp-image-editor.php';
require_once ABSPATH . WPINC . '/class-wp-image-editor-gd.php';

/**
 * Tests for the `_wp_make_subsizes()` function.
 *
 * @group image
 * @group media
 * @group upload
 *
 * @covers ::_wp_make_subsizes
 */
class Tests_Image_MakeSubsizes extends WP_UnitTestCase {

	public function set_up() {
		parent::set_up();

		require_once ABSPATH . 'wp-admin/includes/image.php';

		if ( ! call_user_func( array( 'WP_Image_Editor_GD', 'test' ) ) ) {
			$this->markTestSkipped( 'The GD image editor is not available.' );
		}
	}

	public function tear_down() {
		remove_all_filters( 'wp_image_editors' );
		$this->remove_added_uploads();

		parent::tear_down();
	}

	/**
	 * Ensures registered sizes that resolve to the same file are generated once.
	 *
	 * Sub-sizes are stored on disk by their dimensions, so two sizes registered
	 * with matching width, height, and crop produce an identical file. They
	 * should be generated a single time and shared by every size name, rather
	 * than re-encoded once per name.
	 *
	 * @ticket 61925
	 *
	 * @covers ::_wp_make_subsizes
	 */
	public function test_identical_sizes_are_generated_once_and_shared() {
		Spy_Make_Subsize_Image_Editor::$make_subsize_count = 0;

		add_filter(
			'wp_image_editors',
			static function () {
				return array( 'Spy_Make_Subsize_Image_Editor' );
			}
		);

		$attachment_id = self::factory()->attachment->create_upload_object( DIR_TESTDATA . '/images/canola.jpg' );

		$file       = get_attached_file( $attachment_id );
		$image_meta = wp_get_attachment_metadata( $attachment_id );

		// Count only the sub-sizes generated by the call under test.
		Spy_Make_Subsize_Image_Editor::$make_subsize_count = 0;

		// Two size names requesting an identical file, plus one distinct size.
		$new_sizes = array(
			'test_dedup_a'  => array(
				'width'  => 40,
				'height' => 40,
				'crop'   => true,
			),
			'test_dedup_b'  => array(
				'width'  => 40,
				'height' => 40,
				'crop'   => true,
			),
			'test_distinct' => array(
				'width'  => 80,
				'height' => 80,
				'crop'   => true,
			),
		);

		$result = _wp_make_subsizes( $new_sizes, $file, $image_meta, $attachment_id );

		$this->assertSame(
			2,
			Spy_Make_Subsize_Image_Editor::$make_subsize_count,
			'Two identical sizes and one distinct size should generate two files, not three.'
		);

		$this->assertArrayHasKey( 'test_dedup_a', $result['sizes'], 'The first identical size should be recorded.' );
		$this->assertArrayHasKey( 'test_dedup_b', $result['sizes'], 'The second identical size should be recorded.' );
		$this->assertSame(
			$result['sizes']['test_dedup_a'],
			$result['sizes']['test_dedup_b'],
			'Both identical size names should reference the same generated file.'
		);
	}
}

/**
 * A GD image editor that counts calls to make_subsize() for the dedup test.
 */
class Spy_Make_Subsize_Image_Editor extends WP_Image_Editor_GD {

	/**
	 * Number of times make_subsize() has been called.
	 *
	 * @var int
	 */
	public static $make_subsize_count = 0;

	public function make_subsize( $size_data ) {
		++self::$make_subsize_count;

		return parent::make_subsize( $size_data );
	}
}
