<?php
/**
 * Autoloader for the bundled PHP AI Client library.
 *
 * This file is generated by tools/php-ai-client/installer.sh.
 * Do not edit directly.
 *
 * @package WordPress
 * @subpackage AI
 * @since 7.0.0
 */

// Load polyfills (each function is guarded by function_exists).
require_once __DIR__ . '/src/polyfills.php';

spl_autoload_register(
	static function ( $class_name ) {
		// Namespace prefix for the AI client.
		$client_prefix    = 'WordPress\\AiClient\\';
		$client_prefix_len = 20; // strlen( 'WordPress\\AiClient\\' )

		// Namespace prefix for scoped dependencies.
		$scoped_prefix     = 'WordPress\\AiClientDependencies\\';
		$scoped_prefix_len = 31; // strlen( 'WordPress\\AiClientDependencies\\' )

		// PSR interface namespaces (not scoped, kept global).
		$psr_prefixes = array(
			'Psr\\Http\\Client\\'        => 16,
			'Psr\\Http\\Message\\'       => 17,
			'Psr\\EventDispatcher\\'     => 21,
			'Psr\\SimpleCache\\'         => 16,
		);

		$base_dir = __DIR__;

		// 1. WordPress\AiClient\* → src/
		if ( 0 === strncmp( $class_name, $client_prefix, $client_prefix_len ) ) {
			$relative_class = substr( $class_name, $client_prefix_len );
			$file           = $base_dir . '/src/' . str_replace( '\\', '/', $relative_class ) . '.php';
			if ( file_exists( $file ) ) {
				require $file;
			}
			return;
		}

		// 2. WordPress\AiClientDependencies\* → third-party/ (strip prefix).
		if ( 0 === strncmp( $class_name, $scoped_prefix, $scoped_prefix_len ) ) {
			$relative_class = substr( $class_name, $scoped_prefix_len );
			$file           = $base_dir . '/third-party/' . str_replace( '\\', '/', $relative_class ) . '.php';
			if ( file_exists( $file ) ) {
				require $file;
			}
			return;
		}

		// 3. Psr\* interfaces → third-party/Psr/...
		foreach ( $psr_prefixes as $prefix => $prefix_len ) {
			if ( 0 === strncmp( $class_name, $prefix, $prefix_len ) ) {
				$relative_class = substr( $class_name, 4 ); // Strip 'Psr\' prefix, keep sub-namespace.
				$file           = $base_dir . '/third-party/Psr/' . str_replace( '\\', '/', $relative_class ) . '.php';
				if ( file_exists( $file ) ) {
					require $file;
				}
				return;
			}
		}
	}
);
