##
# A reusable workflow that runs the PHPUnit test suite with the specified configuration.
#
# This workflow is used by `trunk` and branches >= 5.9.
##
name: Run PHPUnit tests

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating system to run tests on'
        required: false
        type: 'string'
        default: 'ubuntu-24.04'
      php:
        description: 'The version of PHP to use, in the format of X.Y'
        required: true
        type: 'string'
      db-type:
        description: 'Database type. Valid types are mysql and mariadb'
        required: false
        type: 'string'
        default: 'mysql'
      db-version:
        description: 'Database version'
        required: false
        type: 'string'
        default: '8.4'
      db-innovation:
        description: 'Whether a database software innovation release is being tested.'
        required: false
        type: 'boolean'
        default: false
      multisite:
        description: 'Whether to run tests as multisite'
        required: false
        type: 'boolean'
        default: false
      memcached:
        description: 'Whether to test with memcached enabled'
        required: false
        type: 'boolean'
        default: false
      phpunit-config:
        description: 'The PHPUnit configuration file to use'
        required: false
        type: 'string'
        default: 'phpunit.xml.dist'
      phpunit-test-groups:
        description: 'A list of test groups to run.'
        required: false
        type: 'string'
        default: ''
      tests-domain:
        description: 'The domain to use for the tests'
        required: false
        type: 'string'
        default: 'example.org'
      coverage-report:
        description: 'Whether to generate a code coverage report.'
        required: false
        type: boolean
        default: false
      report:
        description: 'Whether to report results to WordPress.org Hosting Tests'
        required: false
        type: 'boolean'
        default: false
      allow-errors:
        description: 'Whether to continue when test errors occur.'
        required: false
        type: boolean
        default: false
    secrets:
      CODECOV_TOKEN:
        description: 'The Codecov token required for uploading reports.'
        required: false
      WPT_REPORT_API_KEY:
        description: 'The WordPress.org Hosting Tests API key.'
        required: false

env:
  LOCAL_DB_TYPE: ${{ inputs.db-type }}
  LOCAL_DB_VERSION: ${{ inputs.db-version }}
  LOCAL_PHP_MEMCACHED: ${{ inputs.memcached }}
  LOCAL_WP_TESTS_DOMAIN: ${{ inputs.tests-domain }}
  PHPUNIT_CONFIG: ${{ inputs.phpunit-config }}
  PUPPETEER_SKIP_DOWNLOAD: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  # Runs the PHPUnit tests for WordPress.
  phpunit-tests:
    name: ${{ ( inputs.phpunit-test-groups || inputs.coverage-report ) && format( 'PHP {0} with ', inputs.php ) || '' }} ${{ 'mariadb' == inputs.db-type && 'MariaDB' || 'MySQL' }} ${{ inputs.db-version }}${{ inputs.multisite && ' multisite' || '' }}${{ inputs.db-innovation && ' (innovation release)' || '' }}${{ inputs.memcached && ' with memcached' || '' }}${{ inputs.report && ' (test reporting enabled)' || '' }} ${{ 'example.org' != inputs.tests-domain && inputs.tests-domain || '' }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.coverage-report && 120 || inputs.php == '8.4' && 30 || 20 }}
    permissions:
      contents: read

    services:
      database:
        image: ${{ inputs.db-type }}:${{ inputs.db-version }}
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_develop_tests
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: wordpress_develop_tests
        ports:
          - 3306
        options: >-
          --health-cmd="${{ inputs.db-type == 'mariadb' && ( contains( fromJSON('["5.5", "10.0", "10.1", "10.2", "10.3"]'), inputs.db-version ) && 'mysqladmin ping -h localhost || exit 1' || 'mariadb-admin ping -h localhost || exit 1' ) || 'mysqladmin ping -h localhost || exit 1' }}"
          --health-interval="30s"
          --health-timeout="10s"
          --health-retries="5"
      memcached:
        image: ${{ inputs.memcached && 'memcached:1.6' || '' }}
        ports:
          - 11211

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'

      - name: Set weekly cache suffix
        id: weekly-cache-suffix
        run: echo "value=$(/bin/date -u --date='last Mon' '+%F')" >> "$GITHUB_OUTPUT"

      - name: Cache npm dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.0.3
        with:
          path: |
            ~/.npm
            node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ steps.weekly-cache-suffix.outputs.value }}
          restore-keys: |
            npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            npm-${{ runner.os }}-

      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '${{ inputs.php }}'
          coverage: xdebug
          extensions: gd, mysqli, memcached

      - name: Install npm dependencies
        run: npm install

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          custom-cache-suffix: ${{ steps.weekly-cache-suffix.outputs.value }}

      - name: Build WordPress
        run: npm run build:dev

      - name: Configure test domain
        run: |
          TESTS_HOST="${LOCAL_WP_TESTS_DOMAIN%%:*}"
          TESTS_PORT="${LOCAL_WP_TESTS_DOMAIN##*:}"

          if [ "${TESTS_HOST}" = "${LOCAL_WP_TESTS_DOMAIN}" ]; then
            TESTS_PORT='80'
          fi

          echo "WP_TESTS_HOST=${TESTS_HOST}" >> "$GITHUB_ENV"
          echo "WP_TESTS_PORT=${TESTS_PORT}" >> "$GITHUB_ENV"

      - name: Prepare wp-tests-config.php
        run: |
          cp wp-tests-config-sample.php wp-tests-config.php

          perl -i -pe "s/youremptytestdbnamehere/wordpress_develop_tests/" wp-tests-config.php
          perl -i -pe "s/yourusernamehere/root/" wp-tests-config.php
          perl -i -pe "s/yourpasswordhere/root/" wp-tests-config.php
          perl -i -pe "s/define\( 'DB_HOST', 'localhost' \);/define( 'DB_HOST', '127.0.0.1:${DB_PORT}' );/" wp-tests-config.php
          perl -i -pe "s/define\( 'WP_TESTS_DOMAIN', 'example.org' \);/define( 'WP_TESTS_DOMAIN', '${LOCAL_WP_TESTS_DOMAIN}' );/" wp-tests-config.php

          if [ "${LOCAL_PHP_MEMCACHED}" = 'true' ]; then
            cp tests/phpunit/includes/object-cache.php src/wp-content/object-cache.php
            echo "\$memcached_servers = array( array( '127.0.0.1', 11211 ) );" >> wp-tests-config.php
          fi
        env:
          DB_PORT: ${{ job.services.database.ports['3306'] }}

      - name: General debug information
        run: |
          apache2 -v
          php --version
          curl --version
          git --version
          locale -a
          mysql --version

      - name: Run external HTTP tests
        if: ${{ ! inputs.multisite && ! inputs.phpunit-test-groups && ! inputs.coverage-report }}
        continue-on-error: ${{ inputs.allow-errors }}
        run: WP_RUN_CORE_TESTS=1 ./vendor/bin/phpunit --verbose -c "${PHPUNIT_CONFIG}" --group external-http

      - name: Run PHPUnit tests${{ inputs.phpunit-test-groups && format( ' ({0} groups)', inputs.phpunit-test-groups ) || '' }}${{ inputs.coverage-report && ' with coverage report' || '' }}
        continue-on-error: ${{ inputs.allow-errors }}
        run: |
          WP_RUN_CORE_TESTS=1 WP_MULTISITE="${WP_MULTISITE}" ./vendor/bin/phpunit \
            --verbose \
            -c "${PHPUNIT_CONFIG}" \
            ${{ inputs.phpunit-test-groups && '--group "${TEST_GROUPS}"' || '' }} \
            ${{ inputs.coverage-report && '--coverage-clover "wp-code-coverage-${MULTISITE_FLAG}-${GITHUB_SHA}.xml"' || '' }}
        env:
          TEST_GROUPS: ${{ inputs.phpunit-test-groups }}
          MULTISITE_FLAG: ${{ inputs.multisite && 'multisite' || 'single' }}
          WP_MULTISITE: ${{ inputs.multisite && '1' || '0' }}

      - name: Run AJAX tests
        if: ${{ ! inputs.phpunit-test-groups && ! inputs.coverage-report }}
        continue-on-error: ${{ inputs.allow-errors }}
        run: WP_RUN_CORE_TESTS=1 ./vendor/bin/phpunit --verbose -c "${PHPUNIT_CONFIG}" --group ajax

      - name: Run ms-files tests as a multisite install
        if: ${{ inputs.multisite && ! inputs.phpunit-test-groups && ! inputs.coverage-report }}
        continue-on-error: ${{ inputs.allow-errors }}
        run: WP_RUN_CORE_TESTS=1 WP_MULTISITE=1 ./vendor/bin/phpunit --verbose -c "${PHPUNIT_CONFIG}" --group ms-files

      # __fakegroup__ is excluded to force PHPUnit to ignore the <exclude> settings in phpunit.xml.dist.
      - name: Run (Xdebug) tests
        if: ${{ ! inputs.phpunit-test-groups && ! inputs.coverage-report }}
        continue-on-error: ${{ inputs.allow-errors }}
        run: WP_RUN_CORE_TESTS=1 ./vendor/bin/phpunit -v -c "${PHPUNIT_CONFIG}" --group xdebug --exclude-group __fakegroup__

      - name: Upload test coverage report to Codecov
        if: ${{ inputs.coverage-report }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: wp-code-coverage${{ inputs.multisite && '-multisite' || '-single' }}-${{ github.sha }}.xml
          flags: ${{ inputs.multisite && 'multisite' || 'single' }},php
          fail_ci_if_error: true

      - name: Ensure version-controlled files are not modified or deleted
        run: git diff --exit-code

      - name: Checkout the WordPress Test Reporter
        if: ${{ github.ref == 'refs/heads/trunk' && inputs.report }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'WordPress/phpunit-test-runner'
          path: 'test-runner'
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Submit test results to the WordPress.org host test results
        if: ${{ github.ref == 'refs/heads/trunk' && inputs.report }}
        env:
          WPT_REPORT_API_KEY: "${{ secrets.WPT_REPORT_API_KEY }}"
          WPT_PREPARE_DIR: ${{ github.workspace }}
          WPT_TEST_DIR: ${{ github.workspace }}
        run: php test-runner/report.php
