##
# A reusable workflow that runs end-to-end tests.
#
# Branches 6.3 and earlier used Puppeteer instead of Playwright.
# Use https://github.com/WordPress/wordpress-develop/tree/6.3/.github/workflows/reusable-end-to-end-tests.yml instead.
##
name: End-to-end Tests

on:
  workflow_call:
    inputs:
      LOCAL_SCRIPT_DEBUG:
        description: 'Whether to enable script debugging.'
        required: false
        type: 'boolean'
        default: false
      php-version:
        description: 'The PHP version to use.'
        required: false
        type: 'string'
        default: 'latest'
      install-gutenberg:
        description: 'Whether to install the Gutenberg plugin.'
        required: false
        type: 'boolean'
        default: true
      gutenberg-version:
        description: 'A specific version of Gutenberg to install.'
        required: false
        type: 'string'
      install-playwright:
        description: 'Whether to install Playwright browsers.'
        required: false
        type: 'boolean'
        default: true

env:
  LOCAL_DIR: build
  LOCAL_PHP: ${{ inputs.php-version }}${{ 'latest' != inputs.php-version && '-fpm' || '' }}

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  # Runs the end-to-end test suite.
  #
  # Performs the following steps:
  # - Sets environment variables.
  # - Checks out the repository.
  # - Sets up Node.js.
  # - Logs debug information about the GitHub Action runner.
  # - Installs npm dependencies.
  # - Install Playwright browsers.
  # - Builds WordPress to run from the `build` directory.
  # - Starts the WordPress Docker container.
  # - Logs the running Docker containers.
  # - Logs Docker debug information (about both the Docker installation within the runner and the WordPress container).
  # - Install WordPress within the Docker container.
  # - Install Gutenberg.
  # - Install additional languages.
  # - Run the E2E tests.
  # - Uploads screenshots and HTML snapshots as an artifact.
  # - Ensures version-controlled files are not modified or deleted.
  e2e-tests:
    name: SCRIPT_DEBUG ${{ inputs.LOCAL_SCRIPT_DEBUG && 'enabled' || 'disabled' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 20

    steps:
      - name: Configure environment variables
        run: |
          echo "PHP_FPM_UID=$(id -u)" >> "$GITHUB_ENV"
          echo "PHP_FPM_GID=$(id -g)" >> "$GITHUB_ENV"
