# A reusable workflow that runs WordPress upgrade testing under the conditions provided.
name: Upgrade Tests

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating system to run tests on.'
        required: false
        type: 'string'
        default: 'ubuntu-24.04'
      wp:
        description: 'The version of WordPress to start with.'
        required: true
        type: 'string'
      new-version:
        description: 'The version of WordPress to update to. Use "latest" to update to the latest version, "develop" to update to the current branch, or provide a specific version number to update to.'
        type: 'string'
        default: 'latest'
      php:
        description: 'The version of PHP to use. Expected format: X.Y.'
        required: true
        type: 'string'
      multisite:
        description: 'Whether to run tests as multisite.'
        required: false
        type: 'boolean'
        default: false
      db-image:
        description: 'The database Docker image to use'
        required: false
        type: 'string'
        default: ''
      db-type:
        description: 'Database type. Valid types are mysql and mariadb. Only used when db-image is not provided.'
        required: false
        type: 'string'
        default: 'mysql'
      db-version:
        description: 'Database version. Only used when db-image is not provided.'
        required: false
        type: 'string'
        default: '5.7'

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  # Runs upgrade tests on a build of WordPress.
  #
  # Performs the following steps:
  # - Sets up PHP.
  # - Downloads the specified version of WordPress.
  # - Creates a `wp-config.php` file.
  # - Installs WordPress.
  # - Checks the version of WordPress before the upgrade.
  # - Updates to the latest minor version.
  # - Updates the database after the minor update.
  # - Checks the version of WordPress after the minor update.
  # - Updates to the version of WordPress being tested.
  # - Updates the database.
  # - Checks the version of WordPress after the upgrade.
  upgrade-tests:
    name: ${{ inputs.wp }} to ${{ inputs.new-version }} / PHP ${{ inputs.php }} with ${{ inputs.db-image || format( '{0}:{1}', inputs.db-type, inputs.db-version ) }}${{ inputs.multisite && ' multisite' || '' }}
    permissions:
      contents: read
    runs-on: ${{ inputs.os }}
    timeout-minutes: 20

    services:
      database:
        image: ${{ inputs.db-image || format( '{0}:{1}', inputs.db-type, inputs.db-version ) }}
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval="30s"
          --health-timeout="10s"
          --health-retries="5"
          -e MYSQL_ROOT_PASSWORD="root"
          -e MYSQL_DATABASE="test_db"

    steps:
      - name: Hello
        run: echo Hello
