name: Failed workflow dispatcher

on:
    workflow_call:
        inputs:
            run_id:
                required: true
                type: string
            ref:
                required: true
                type: string

jobs:
    dispatch:
        name: Dispatch failed-workflow
        runs-on: ubuntu-24.04
        permissions:
            actions: write
        steps:
            - name: Dispatch workflow run
              uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
              with:
                  retries: 2
                  retry-exempt-status-codes: 418
                  script: |
                      github.rest.actions.createWorkflowDispatch({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      workflow_id: 'failed-workflow.yml',
                      ref: '${{ inputs.ref }}',
                      inputs: {
                          run_id: '${{ inputs.run_id }}',
                      }
                      });
