##
# A reusable workflow that runs PHP Static Analysis tests.
##
name: PHP Static Analysis

on:
  workflow_call:
    inputs:
      php-version:
        description: 'The PHP version to use.'
        required: false
        type: 'string'
        default: 'latest'

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  # Runs PHP static analysis tests.
  #
  # Violations are reported inline with annotations.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up PHP.
  # - Logs debug information.
  # - Installs Composer dependencies.
  # - Configures caching for PHP static analysis scans.
  # - Make Composer packages available globally.
  # - Runs PHPStan static analysis (with Pull Request annotations).
  # - Saves the PHPStan result cache.
  # - Ensures version-controlled files are not modified or deleted.
  phpstan:
    name: Run PHP static analysis
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Set up PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: cs2pr

      # This date is used to ensure that the Composer cache is cleared at least once every week.
      # http://man7.org/linux/man-pages/man1/date.1.html
      - name: "Get last Monday's date"
        id: get-date
        run: echo "date=$(/bin/date -u --date='last Mon' "+%F")" >> "$GITHUB_OUTPUT"

      - name: General debug information
        run: |
          npm --version
          node --version
          composer --version

      # Since Composer dependencies are installed using `composer update` and no lock file is in version control,
      # passing a custom cache suffix ensures that the cache is flushed at least once per week.
      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
        with:
          custom-cache-suffix: ${{ steps.get-date.outputs.date }}

      - name: Make Composer packages available globally
        run: echo "${PWD}/vendor/bin" >> "$GITHUB_PATH"

      - name: Install npm dependencies
        run: npm ci --ignore-scripts

      - name: Build WordPress
        run: npm run build:dev

      - name: Cache PHP Static Analysis scan cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: .cache # This is defined in the base.neon file.
          key: "phpstan-result-cache-${{ github.run_id }}"
          restore-keys: |
            phpstan-result-cache-

      - name: Run PHP static analysis tests
        id: phpstan
        run: composer run phpstan -- -vvv --error-format=checkstyle | cs2pr --errors-as-warnings --graceful-warnings

      - name: "Save result cache"
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        if: ${{ !cancelled() }}
        with:
          path: .cache
          key: "phpstan-result-cache-${{ github.run_id }}"

      - name: Ensure version-controlled files are not modified or deleted
        run: git diff --exit-code
