name: Third Party Library Changes

on:
  pull_request:
    paths:
      - 'src/wp-includes/ID3/**'
      - 'src/wp-includes/IXR/**'
      - 'src/wp-includes/PHPMailer/**'
      - 'src/wp-includes/Requests/**'
      - 'src/wp-includes/SimplePie/**'
      - 'src/wp-includes/sodium_compat/**'
      - 'src/wp-includes/Text/**'

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  third-party-changed-files:
    runs-on: ubuntu-latest
    name: Get third party library modified files
    permissions:
      issues: write
      pull-requests: write
    if: ${{ github.repository == 'johnbillion/wordpress-develop' }}
    steps:
      - name: Leave a comment about third party libraries
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.issue;

            // Check for the presence of a comment and bail early.
            const comments = ( await github.rest.issues.listComments( { owner, repo, issue_number: number } ) ).data;

            const hasComment = comments.some( comment =>
              comment.user.type === 'Bot' && comment.body.includes( 'Third Party Files' )
            );

            if ( hasComment ) return;

            github.rest.issues.createComment( {
              owner,
              repo,
              issue_number: number,
              body: `## Third Party Files
            This pull request modifies a third party library file. Changes to files in the following directories should be made to their respective upstream projects instead:

            - \`src/wp-includes/ID3\`: [ID3](https://example.com)
            - \`src/wp-includes/IXR\`: [IXR](https://example.com)
            - \`src/wp-includes/PHPMailer\`: [PHPMailer](https://example.com)
            - \`src/wp-includes/Requests\`: [Requests](https://example.com)
            - \`src/wp-includes/SimplePie\`: [SimplePie](https://example.com)
            - \`src/wp-includes/sodium_compat\`: [Sodium Compat](https://example.com)
            - \`src/wp-includes/Text\`: [Text](https://example.com)

            These changes need to be proposed and merged into the upstream projects before being included in WordPress.
              `,
            } );

      - name: Fail the workflow run
        run: exit 1
